set-option -g default-shell $SHELL
set -as terminal-features ",xterm-256color:RGB"
setw -g mouse on


# Pane Splitting
unbind '"'
unbind '%'
bind -n M-> split-window -h
bind -n M-. split-window -v

# Pane Sizing
bind -n M-H resize-pane -L
bind -n M-J resize-pane -D
bind -n M-K resize-pane -U
bind -n M-L resize-pane -R

# Pane Switching
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-\; last-pane


# Window Settings
set -g base-index 1

# Window Switching (9 windows)
bind -n M-1 selectw -t:=1
bind -n M-2 selectw -t:=2
bind -n M-3 selectw -t:=3
bind -n M-4 selectw -t:=4
bind -n M-4 selectw -t:=5
bind -n M-4 selectw -t:=6
bind -n M-4 selectw -t:=7
bind -n M-4 selectw -t:=8
bind -n M-4 selectw -t:=9

# Window Mutation
bind -n M-Space new-window
bind -n M-Tab last-window
bind -n M-- confirm-before -p "Kill pane #P? (y/n)" kill-pane
bind -n M-= confirm-before -p "Kill window #W? (y/n)" kill-window


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
